name: Build Docker Images with Matrix

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build (default: main)"
        required: false
        default: "main"

jobs:
  build-docker-images:
    runs-on: ubuntu-latest

    # Define the matrix for repositories
    strategy:
      matrix:
        repo:
          - frontend-repo
          - backend-repo
          - another-app-repo

    steps:
      # Checkout code for each repository
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: your-org-or-username/${{ matrix.repo }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.inputs.branch || 'main' }}

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Docker Image
      - name: Build and Tag Docker Image
        run: |
          docker build -t your-org-or-username/${{ matrix.repo }}:latest .
          docker tag your-org-or-username/${{ matrix.repo }}:latest your-dockerhub/${{ matrix.repo }}:latest

      # Push Docker Image
      - name: Push Docker Image to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push your-dockerhub/${{ matrix.repo }}:latest
