name: 05- Central Docker Image Build

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "Repository name"
        required: true
      branch:
        description: "Branch to build from"
        required: true
        default: "main"
      directory:
        description: "Directory name where Dockerfile exists"
        required: true

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout the specified repository and branch
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: arunponugoti1/${{ github.event.inputs.repo }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.inputs.branch }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Docker Image
      - name: Build Docker Image
        run: |
          cd ${{ github.event.inputs.directory }}
          docker build -t your-dockerhub/${{ github.event.inputs.repo }}:latest .
          docker tag your-dockerhub/${{ github.event.inputs.repo }}:latest your-dockerhub/${{ github.event.inputs.repo }}:latest

      # Push Docker Image to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push your-dockerhub/${{ github.event.inputs.repo }}:latest
