name: Manual Docker Image Build

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "Repository name"
        required: true
      branch:
        description: "Branch to build from"
        required: true
        default: "main"
      directory:
        description: "Directory name"
        required: true

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: your-org-or-username/${{ github.event.inputs.repo }}/${{ github.event.inputs.directory }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t your-dockerhub/${{ github.event.inputs.repo }}:latest .
          docker tag your-dockerhub/${{ github.event.inputs.repo }}:latest your-dockerhub/${{ github.event.inputs.repo }}:latest

      - name: Push Docker Image
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run: docker push your-dockerhub/${{ github.event.inputs.repo }}:latest
