name: Build Docker Image

on:
  workflow_dispatch:  # Allows you to manually trigger this workflow from GitHub

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t my-app:latest .

      # Step 4: Save the Docker image to a file
      - name: Save Docker Image as a .tar file
        run: |
          docker save my-app:latest > my-app.tar

      # Step 5: Upload the Docker image as an artifact
      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-app-image
          path: my-app.tar
